### ISSUE TITLE
Bug: w/ Published Version of 1.1.2

### ISSUE THREAD

**Issue by nmccready** [mezzario/color-math#2]
```
❯ node
> const colorMath = require('color-math');
undefined
> colorMath.evaluate('#ffcc00 - 20')
{ withAst: false,
  astWithLocs: false,
  evaluator: 'evaluator.core',
  expr: '#ffcc00 - 20',
  program:
   Program {
     '$type': 'program',
     '$loc': Loc { start: [Object], end: [Object] },
     statements: [ [Object] ],
     '$eval': Color { _rgb: [Array] } },
  result: Color { _rgb: [ 255, 204, 0, 1, _clipped: false ] },
  resultStr: '#ffcc00',
  astStr: null,
  error: null }
>
```

Expecting resultStr to be `#ebb800`

![Screen Shot 2019-07-29 at 11 02 22 AM](https://user-images.githubusercontent.com/583593/62059009-6e29a080-b1f0-11e9-925c-361a389a7243.png)

Is this related to #1  ?

**Comment by nmccready** [comment]
So I tried this against a scoped published version against the linting fixes and I still am getting this same problem. These errors are only occurring from the my consuming project and not within color-math itself (as locally it works fine). 

There must be some kind of version collision of a dependency.

**Comment by nmccready** [comment]
This is still an issue, but I am unsubscribing as I switched to just using chroma-js instead.

**Comment by mezzario** [comment]
@nmccready hey, thank you for reporting this. i just updated all packages to latest version, fixed tests, module casing and looks like it solved problem you described above also:

https://runkit.com/vencedor/5d44ec2dd6713400135e6247

all the best! :)
